version: "3"
services:
  currency-exchange-spring-boot-backend:
    image: currency-exchange-spring-boot-backend
    restart: always
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1111
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    volumes:
      -  /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: rate_exchange
      MYSQL_ROOT_PASSWORD: 1111